spring:
  application:
    name: Restro Application

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update